### ISSUE TITLE
production ready and storage/retrieval as protobuf -- no json conversion

### ISSUE THREAD

**Issue by bcardarella** [mpartel/postgres-protobuf#7]
We are using protobuf to transmit real-time telemetry of watercraft over GSM. We'd be interested in storing the original protobuf messages rather than decoding so I'm curious if your lib supports the following:

1. is this mature enough to suggest for production use
2. can we query the protobuf columns for data?
3. can we avoid the serialiation to/from JSON and just export pure protobuf
4. we are considering using TimescaleDB and we'd like to rely on their aggregate functions... do you happen to now if this would be compatible?

**Comment by mpartel** [comment]
1. I've used it in production without major issues, but I wouldn't go so far as to call it mature or well tested. See the list of caveats in the readme. That said, Postgres's process model should limit potential damage.
2. Yes, examples in readme.
3. Yes, the protobufs live in ordinary `bytea` columns. This extension only provides functions.
4. I don't know TimescaleDB, but since you can query data from protobufs, I'd imagine you can pass the results to whatever aggregate functions you want.

**Comment by bcardarella** [comment]
Thank you :)
